olsrd:  fix compilation with bison version 3.7.1
Recent bison versions changed the way the parser output is generated,
which causes compilation of the generated oparse.c to fail with

[CC] src/cfgparser/oparse.c
src/cfgparser/oparse.c:265:10: fatal error: oparse.h-tmp: No such file
or directory
 #include "oparse.h-tmp"
          ^~~~~~~~~~~~~~

Fix the issue by generating the expected output files directly and by
modifying the *.c file in-place.

Suggested-by: Jo-Philipp Wich <jo@mein.io>
Signed-off-by: Nick Hainke <vincent@systemli.org>